Реализация add-controllers
girisn/java-shareit pull request #1
Opened 2023-06-24 10:41 UTC by girisn

Увлеклась идеей сделать что-то похожее на работу с репозиториями из spring-data-jpa )) сервисы пошли туда же за компанию, чтобы не писать один и тот же код кучу раз, только жаль, что приходится использовать приведение типов, чтобы добраться до функций в ItemRepository

2023-06-24 10:45 UTC, girisn commented
=_= я сделала такую красоту, а эта падла не пропускает мой код по тупым причинам. обидно

2023-06-24 10:53 UTC, girisn commented
E = ID, M = MODEL, D = DTO

2023-06-24 18:01 UTC, EugeneLenkevich requested changes
Привет, Наталия, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-06-24 18:05 UTC, EugeneLenkevich commented
> Увлеклась идеей сделать что-то похожее на работу с репозиториями из spring-data-jpa )) сервисы пошли туда же за компанию, чтобы не писать один и тот же код кучу раз, только жаль, что приходится использовать приведение типов, чтобы добраться до функций в ItemRepository

Очень прикольно получилось и оригинально  
Единственное тут главное не перемудрить и не переусложнить, хотя... в учебном проекте наоборот надо пробовать все :)
И еще моментик - спринговые репозитории работают достаточно хитро, там не только дженерики и пр, там вообще все довольно сложно, можно почитать ради интереса
https://stackoverflow.com/questions/38509882/how-are-spring-data-repositories-actually-implemented

2023-06-25 07:09 UTC, girisn commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        Optional<Item> item = repository.findById(model.getId());
Конкретно здесь не получится, потому что мне надо искать Item не по id и userId, а конкретно по id, и только потом проверять, что userId соответствует ожидаемому. В моем понимании такая проверка - это все же уровень сервиса. Иначе в доп функции репозитория пришлось бы писать 
Item item = storage.findById(id);
if (!item.getUserId().equals(userId))
  throw ...

2023-06-25 12:12 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-07-27 16:35 UTC, merged