ТЗ 15
girisn/java-shareit pull request #5
Opened 2023-08-22 06:50 UTC by girisn

2023-08-22 08:20 UTC, EugeneLenkevich requested changes
Привет, Наталия, спасибо за PR

Отличная работа, спасибо! Хотелось бы только причесать немного логирование :)

2023-08-23 07:17 UTC, girisn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
Я делала это в спринте 14) Хотела оставить как есть, это было красиво, но там опять какие-то CI/CD проверки пошли непонятные, я в итоге изменила обратно

2023-08-23 07:35 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
А я уж и не помню)

2023-08-26 13:51 UTC, girisn commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                 @RequestParam(defaultValue = "ALL") String state,
Можно было бы, если бы не было проверки на валидность подаваемого значения. Нужно обрабатывать случай, где вместо известного значения, прописанного в State, передается неизвестное :(

2023-08-26 13:55 UTC, girisn commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Item created by user with ID = {} ", userId);
Да, поняла, согласна. Наверное нет особого смысла в контроллерах вообще что-то логировать, учитывая то, что есть логирование на уровне сервисов

2023-08-26 16:34 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-08-26 16:52 UTC, merged